# 第四、五章笔记

## 一.强制类型转换

### 1.static_cast

> 使用条件：任何一个不包含**底层const（数组和指针最前面的const）**的对象都支持static_const

```c++
int a = 0;
double b = static_cast<double>(a);

```

### 2.const_cast

> 只能改变对象的底层const（指针和数组最前面的const）

```c++
const char* a = "helloworld";
char* b  = const_cast<char*>(a);
```



### 3.reinterpret_cast

> 在运算对象的位模式下提供较低层次的重新解释，有很多隐患，不应该使用。

## 二.异常处理

> 异常值存在于运行时的反常行为

### 1.throw表达式

抛出异常

```c++
if(a!=b)
    throw runtime_error("a和b不相等");
```

其中runtime_error是异常的类型名，throw后面接的是runtime_error类型的一个实例。

**大部分异常类型都在<stdexcept>标准库中的std命名空间里面**

### 2.try-catch语句块

```c++
try{
    
}
catch(类型名)
{
    //异常处理
}
catch(类型名){
    //异常处理
}

```

```c++
//eg
#include<iostream>
#include<stdexcept>
using std::cin;
using std::cout;
using std::endl;
using std::domain_error;
int main() {
	unsigned a, b;
	while (cin >> a >> b) {
		try {
			if (b == 0)
				throw domain_error("b不能为0");
			cout << a / b << endl;
			break;
		}
		catch(domain_error err_a) {
			cout << err_a.what() << endl;
			cout << "try again?Enter y or n" << endl;
			char c;
			cin >> c;
			if (c == 'n')
				break;
		}
	}
}
```

几个注意点：

1. catch括号中的为另外一种实例化的方式。
2. catch下面的err_a.what()为打印throw的信息，对于上面例子来说，就是“b不能为0”。所有类型的异常都可以这样
3. try语句中，throw抛出异常后，try中剩下的语句不再继续执行，而是直接跳转到catch中
4. char类型无法接收中文，所以不能用中文。但是string类型可以处理中文

### 3.异常类型

```
<stdexcept>库std命名空间中定义的异常类型
exception	最常见的问题	
runtime_error	只有在运行时才能检测出的问题	
range_error	运行时错误:生成的结果超出了有意义的值域范围	
overflow_error	运行时错误:计算上溢	
underflow_error	运行时错误:计算下溢	
logic_error	程序逻辑错误	
domain_error	逻辑错误:参数对应的结果值不存在	
invalid_argument	逻辑错误:无效参数	
length_error	逻辑错误:试图创建一个超出该类型最大长度的对象	
out_of_range	逻辑错误:使用一个超出有效范围的值
```

注意：runtime_error是range_error、overflow_error、underflow_error的父类。logic_error是domain_error、invalid_argument、length_error、out_of_range的父类。

